ContosoUniversity/Models/Courses.cs
using System;
using System.Collections.Generic;

namespace ContosoUniversity.Models
{
    public partial class Courses
    {
        public int CourseId { get; set; }
        public int Credits { get; set; }
        public string Title { get; set; }
    }
}

ContosoUniversity/Models/Enrollments.cs
using System;
using System.Collections.Generic;

namespace ContosoUniversity.Models
{
    public partial class Enrollments
    {
        public int EnrollmentId { get; set; }
        public int CourseId { get; set; }
        public string Grade { get; set; }
        public int StudentId { get; set; }
    }
}

ContosoUniversity/Models/Students.cs
using System;
using System.Collections.Generic;

namespace ContosoUniversity.Models
{
    public partial class Students
    {
        public int Id { get; set; }
        public DateTime? EnrollmentDate { get; set; }
        public string FirstMidName { get; set; }
        public string LastName { get; set; }
    }
}

ContosoUniversity/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContosoUniversity.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

ContosoUniversity/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContosoUniversity.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

ContosoUniversity/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContosoUniversity.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ContosoUniversity/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContosoUniversity.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

ContosoUniversity/Pages/Student.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ContosoUniversity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using RestSharp;

namespace ContosoUniversity
{
    public class StudentModel : PageModel
    {
        public ConnnectApi ConnApi;
        public StudentModel(IOptions<ConnnectApi> option) {
            ConnApi = option.Value;
        }
        public void OnGet()
        {
            string url = string.Format("{0}/StudentCRUD", ConnApi.WebApi);
            var client = new RestClient(url);
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);
            List<Students> studentList = Tool.getHelper().DeserializeJsonToList<Students>(response.Content);
            ViewData["studentList"] = studentList;
        }

        [HttpPost]
        public  ActionResult DeleteStu(string Fid)
        {
            return null;
        }

    }
}

ContosoUniversity/Pages/StudentRegister.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ContosoUniversity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using RestSharp;

namespace ContosoUniversity.Pages {
    public class StudentRegisterModel : PageModel {
        public ConnnectApi ConnApi;

        public StudentRegisterModel(IOptions<ConnnectApi> options) {
            ConnApi = options.Value;
        }


        public void OnGet() {

        }

        public void OnPostFirst(string lastname,string firstname) {
            Students student = new Students() {
                FirstMidName = firstname,
                LastName = lastname
            };
            string url = string.Format("{0}/StudentCRUD", ConnApi.WebApi);
            var client = new RestClient(url);
            var request = new RestRequest(Method.POST);
            request.AddHeader("content-type", "application/Json");
            request.AddParameter("application/Json", Tool.getHelper().SerializeObject(student), ParameterType.RequestBody);
            IRestResponse response = client.Execute(request);
            ViewData["studentsNew"] = Tool.getHelper().DeserializeJsonToObject<Students>(response.Content);
        }
    }
}

ContosoUniversity/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

ContosoUniversity/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ContosoUniversity/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="jumbotron">
        <h1>Contoso University</h1>
    </div>
    <div class="row">
        <div class="col-md-4">
            <h2>Welcome to Contoso University</h2>
            <p>
                Contoso University is a sample application that
                demonstrates how to use Entity Framework Core in an
                ASP.NET Core Razor Pages web app.
            </p>
        </div>
        <div class="col-md-4">
            <h2>Build it from scratch</h2>
            <p>You can build the application by following the steps in a series of tutorials.</p>
            <p>
                <a class="btn btn-default"
                   href="https://docs.microsoft.com/aspnet/core/data/ef-rp/intro">
                    See the tutorial &raquo;
                </a>
            </p>
        </div>
        <div class="col-md-4">
            <h2>Download it</h2>
            <p>You can download the completed project from GitHub.</p>
            <p>
                <a class="btn btn-default"
                   href="https://github.com/aspnet/Docs/tree/master/aspnetcore/data/ef-rp/intro/samples/cu-final">
                    See project source code &raquo;
                </a>
            </p>
        </div>
    </div>

ContosoUniversity/Pages/Student.cshtml
@page
@model StudentModel
@{
    ViewData["Title"] = "Student";
}
<script src="js/DeleteStudent.js"></script>
<div>
    <table>
        <tr>
            <td>Id</td>
            <td>姓</td>
            <td>名</td>
        </tr>
        @foreach (var students in ViewData["studentlist"] as List<ContosoUniversity.Models.Students>) {
            <tr>
                <td>
                    @students.Id
                </td>
                <td>
                    @students.FirstMidName
                </td>
                <td>
                    @students.LastName
                </td>
                <td>
                    <button type="button" id="delete" onclick="deletethis(@students.Id)">删除</button>
                </td>
            </tr>
        }
    </table>
</div>

ContosoUniversity/Pages/StudentRegister.cshtml
@page
@using Models
@model StudentRegisterModel
@{
    Students stu=new Students();
}
<form id="RegisterForm" method="post" asp-page-handler="First">
    <div>
        <label>姓氏</label>
        <input type="text" name="LastName"/>
    </div>
    <div>
        <label>名字</label>
        <input type="text" name="FirstName" />
    </div>
    <div>
        @*<input type="button" id="Submit" onclick="SubmitData()"/>*@
        <button type="submit">submit</button>
    </div>
</form>

@*<table>
    <tr>
        <td>Id</td>
        <td>姓</td>
        <td>名</td>
    </tr>
    @foreach (Students stuNew in ViewData["studentNew"] as List<Students>)
    {
        <tr>
            <td>
                @stuNew.Id
            </td>
            <td>
                @stuNew.FirstMidName
            </td>
            <td>
                @stuNew.LastName
            </td>
        </tr>
    }
</table>*@

ContosoUniversity/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contoso University</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">Contoso University</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Student">Students</a></li>
                    <li><a asp-page="/Courses/Index">Courses</a></li>
                    <li><a asp-page="/Instructors/Index">Instructors</a></li>
                    <li><a asp-page="/Departments/Index">Departments</a></li>
                    <li><a asp-page="/StudentRegister">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Contoso University</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>    
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>